### ISSUE TITLE
Top level make does link?

### ISSUE THREAD

**Issue by ljreder** [JPLOpenSource/STARS#2]
@garthwatney trying to do a new build within my virtual python environment and find that it will not link.

gcc -o test Simple.o SimpleImpl.o main.o testDrv.o sendEvent.o -L../../../../QHsm -lqhsm
/usr/bin/ld: cannot find -lqhsm: No such file or directory

Attached is a log of the make run.

[make.log](https://github.com/user-attachments/files/16941077/make.log)

I am doing this on my home system 76 box and it previously build fine.

**Comment by garthwatney** [comment]
Fixed in 3a37e4f79087eb410bd9748dfb64e70ed2b44980

**Comment by ljreder** [comment]
ARE THESE PUSHED TO MAIN?

**Comment by garthwatney** [comment]
YesSent from my iPhoneOn Sep 11, 2024, at 5:39 PM, Leonard J. Reder ***@***.***> wrote:﻿
ARE THESE PUSHED TO MAIN?
